export const Theme = {
	colors: {
		background: '#F6F1E8',
		text: '#18124D',
		primary: '#2F36FF',
		secondary: '#DDF4FF',
		muted: '#6E6A96',
		surface: '#FFFDF8',
		border: '#18124D',
		accent: '#FFE88A',
		accentAlt: '#ff9fe5',
	},
	neobrutalism: {
		borderWidth: 2,
		borderRadius: 8,
		shadowOffset: { width: 5, height: 5 },
		shadowOpacity: 1,
		shadowRadius: 0,
		shadowColor: '#000000',
		spacing: 24,
		gap: 16,
		cardBorder: 2,
		thinBorder: 1,
	},
	typography: {
		// fontFamily: 'Inter', WIP
		fontWeightLight: '300' as const,
		fontWeightRegular: '400' as const,
		fontWeightBold: '700' as const,
		fontWeightBlack: '900' as const,
		letterSpacingTight: -0.5,
		letterSpacingNormal: 0,
		letterSpacingWide: 1.2,
	},
};
